# Phase 1 — HTTP uniquement (utilisé pendant la provisioning du certificat)
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # ACME challenge Certbot (webroot)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    server_tokens off;
    access_log /dev/stdout;
    error_log  /dev/stderr warn;
}
